---
title: "S017: AHL influence on RFP and copy #"
author: "Prashant"
date: "July 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, fig.width = 14/3, fig.height = 11.34/3)
source('./general_functions_plate_reading.R')
```

## Input data


Copy the tables of GFP, OD, Sample names etc. in excel and run the command below to get it into R

```{r input data, echo = F, message = F}
# User inputs: 1. Enter name of the excel file, 2. Name of the data sheet(S) 3. number of rows and columns in plate reader data 4. Title for plots #comment (file name starts in the previous directory of this Rproject)

flnm <- 'S017_inspect RFP_18-7-19'

flpath <- str_c('../',flnm,'.xlsx')
fl <- read_plateReader_file(flpath) # load all non empty sheets of the excel file into fl - as a list 
data_sheet1 <- fl$Sheet2 # extract the sheet of interest (sheet2 is by default the first non-empty sheet unless it was renamed)
n_Rows <- 3; 
n_Cols <- 12;

# Context: 23 rows of lines before data is seen, 26 rows between data and fluorescence values, 26 more rows till RFP values (including the row with <>); If partial plate is read there is 1 extra line in all 3 places

if(n_Rows == 8 & n_Cols == 12) {b_gap = 23; a_gap <- 26;
}  else {b_gap = 24; a_gap <- 27}
 


table_OD <- data_sheet1[b_gap + 0:n_Rows, 1 + 0:n_Cols] # exract the OD table
table_Samples <- data_sheet1[b_gap + 0:n_Rows, 3 + n_Cols + 0:n_Cols] # exract the Sample names table
table_Inducer <- data_sheet1[b_gap + 0:n_Rows, 5+2*n_Cols + 0:n_Cols] # exract the Inducer table
table_GFP <- data_sheet1[(b_gap + a_gap - 1 +n_Rows) + 0:n_Rows, 1 + 0:n_Cols] # exract the GFP values
table_RFP <- data_sheet1[(b_gap + 2*a_gap - 2 +2*n_Rows) + 0:n_Rows,  1 + 0:n_Cols] # exract the RFP values

tables_list <- list(table_Samples,table_OD,table_GFP,table_RFP,table_Inducer)
names_vector <- c('Samples','OD','GFP','RFP','Inducer')

merged1 <- map2_dfc(tables_list, names_vector, read_plate_to_column) # convert plate tables into columns and merge all four data types into 1 table
merged1 %<>% mutate_at(c('OD','GFP','RFP'),as.numeric)  # convert the OD, GFP and RFP into numbers (they are loaded as characters)
```

## Data crunching

Doing calculations with the tables, relating sample names with the values

```{r data analysis, echo=FALSE}
merged2 <- merged1 %>% filter(!str_detect(Samples, "NA|MG"))  # remove NA samples (empty wells)
# merged2 %<>% mutate(Samples = as_factor(Samples), Inducer = as_factor(Inducer)) # freeze order of samples as in the plate - columnwise - for easy plotting
merged2$Inducer %<>% str_c(.,' uM') %>% as_factor()

merged2 %<>% mutate('GFP/RFP' = GFP/RFP, 'GFP/OD' = GFP/OD, 'RFP/OD' = RFP/OD) %>% separate(Samples, c('Samples', NA), sep ='\\+') %>% mutate(Samples = as_factor(Samples)) # calculate ratios and # remove the common reporter plasmid name after the + sign

plotting_order <- group_and_summarize_at(merged2, 'GFP/OD') %>% filter(str_detect(Inducer,'AHL')) %>% arrange(mean) %>% ungroup() %>%  mutate(Samples = fct_inorder(Samples)) %>% pull(Samples) %>% levels() # determine plotting order: based on ascending order of uninduced GFP/OD values

merged2$Samples %<>% fct_relevel('pSH001 ','pRV01 ') # change sample order: manually (# good practice : in ascending order of GFP/OD)
```

## Data tables

Showing raw data and processed data here 

GFP/RFP values
``` {r}
#merged2 # format with colours etc for good visualization in the future
```


## Plotting

Plotting GFP/OD and RFP/OD

```{r plotting2, echo=F}
grouped2 <- merged2 %>% group_and_summarize_at(c('GFP/OD','RFP/OD')) %>% filter(str_detect(Inducer,'None|AHL')) # calculate mean and sd of desired variables

grouped2 %>% ggplot(aes(Samples, mean, color = Measurement, shape = Inducer)) + geom_point(size = 3) + geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = 0.05) + scale_shape_manual(values = c(1,19)) + ggtitle('AHL influence on RFP') + ylab('Fluorescence/OD (a.u.)') -> plt
plt2 <- plt %>% format_classic(.) #%>% format_logscale()
plt2
# ggsave('plots and data/S010_faceted.png', height = 3.5, width = 14)
```

Logscale GFP/OD and RFP/OD

```{r plotting2l, echo=F}
plt2l <- format_logscale(plt2)
plt2l
```

Plotting OD

```{r plotting3}
grouped3 <- merged2 %>% group_and_summarize_at('OD') # calculate mean and sd of OD
grouped3 %>% ggplot(aes(Samples, mean, color = Inducer)) + geom_point(size = 3) + geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = 0.05) + scale_shape_manual(values = c(1,19)) + ggtitle('AHL influence on RFP') + ylab('OD 600') -> plt
plt2 <- plt %>% format_classic(.)
plt2
# ggsave('plots and data/S010_faceted.png', height = 3.5, width = 14)
```

Plotting GFP/RFP

```{r plotting4, echo=F}
sel_table4 <- merged2 %>% group_and_summarize_at() # filter neccesary samples for plotting ; by default mean and variance of GFP/RFP column


sel_table4 %>% ggplot(aes(Samples, mean, color = Inducer)) + geom_point(size = 3) + geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = 0.05) + scale_shape_manual(values = c(1,16)) -> plt
plt %<>% format_classic(.) %>% format_logscale()
plt <- plt + ggtitle('S013 : RBS library 7.2') + ylab('GFP/RFP')
plt
# ggsave('plots and data/S010_faceted.png', height = 3.5, width = 14)
```