---
author: "Prashant Kalvapalle"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

---
title: `r title_name`
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 5, fig.height = 4)

```

## Plotting

### GFP

```{r plot1}
gfp_order_processed.data <- processed.data %>% 
  arrange(GFP) %>% 
  ungroup() %>% 
  mutate(across(Samples, fct_inorder))

gfp_unique_mean <- gfp_order_processed.data %>% 
  select(Samples, contains('mean')) %>% 
  unique()

# plot a horizontal bar graph, along with individual replicates and mean annotated
plt_GFP <- ggplot(data = gfp_order_processed.data,
                  mapping = aes(y = Samples, x = GFP)) + 
  geom_jitter(width = 0, height = .3) + # plot individual replicates
  
 
  # Indicate a light grey bar for the mean - to aid the eye
  geom_bar(data = gfp_unique_mean, 
           aes(x = GFP_mean, y = Samples), alpha = 0.3, fill = 'gray', stat = 'identity',position = 'dodge') +
    # geom_segment(aes(x = GFP_mean, xend = 0, yend = Samples), alpha = 0.1, colour = 'red') + 
  xlab('GFP (a.u)') + ylab('') + ggtitle('Fluorescence measurement', subtitle = 'Plasmids')
  
{plt_GFP + 
    
    # plot mean as a vertical dash (for small point, use size = 0.5)
    geom_point(data = gfp_unique_mean, 
               aes(x = GFP_mean), size = 5, shape = '|') +
    
    # add a text label for quick reference of the mean
    geom_text(data = gfp_unique_mean,  
              mapping = aes(x = GFP_mean, label = GFP_mean %>% round, 
                            hjust = if_else(GFP_mean > max(GFP_mean)/2, 1.3, -0.3)))
  } %>% 
  print()

# ggsave(str_c('./plots and data/', title_name, '.png'), width = 5, height = 4) # save plot if necessary

plotly::ggplotly(plt_GFP) %>% plotly::style(textposition = 'top right')

```

### all fluorescence (normalized)

```{r allfluor}
long_fluor.normalized_processed <- processed.data %>% 
  select(sample_specific_variables, matches('/OD')) %>%  # choose OD, x/OD and _bs and _mean additions
  mutate(index = row_number(), .after = 2) %>% # add a dummy index -- to keep replicates apart
  
  rename_with(.cols = !matches('_mean|Samples|Inducer|index'), .fn = ~ str_c(.x, '_value') ) %>%  # suffix 'value' for non mean columns

  pivot_longer(cols = -c(sample_specific_variables, index), # pull measurement types and summary type (mean vs 'raw' value) into two cols
               names_pattern = '(.*)_(....*)', names_to = c('Measurement', 'type_of_summary')) %>% 
  
  pivot_wider(names_from = type_of_summary, values_from = value) # bring values and means into two separate cols

long_unique_processed <- select(long_fluor.normalized_processed, -c(value, index)) %>% unique()

plt_all_fluor <- ggplot(data = long_fluor.normalized_processed,
                  mapping = aes(y = Samples, x = value)) + 
  geom_jitter(width = 0, height = .3) + # plot individual replicates
  
  # plot mean as a vertical dash (for small point, use size = 0.5)
  geom_point(data = long_unique_processed,
             aes(x = mean), size = 5, shape = '|') + 
  # Indicate a light grey bar for the mean - to aid the eye
  geom_bar(data = long_unique_processed, 
           aes(x = mean, y = Samples), alpha = 0.3, fill = 'gray', stat = 'identity',position = 'dodge') +
  
  facet_grid(~ Measurement, space = 'free', scale = 'free') +
    # geom_segment(aes(x = GFP_mean, xend = 0, yend = Samples), alpha = 0.1, colour = 'red') + 
  xlab('Value') + ylab('') + ggtitle('Fluorescence measurement', subtitle = 'Plasmids')
  
  {plt_all_fluor + geom_text(data = long_unique_processed,  
              mapping = aes(x = mean, label = mean %>% round, 
              hjust = if_else(mean > max(mean)/2, 1.3, -0.3)))
  } %>% 
print()

```

## Data tables

Baseline fluorescence that was subtracted before plotting 

``` {r datadisplay}
# kable(processed.data, caption = 'full data') # format with colours etc for good visualization

kable(empty_cells_baseline) # show baseline data

```

check for processed data as a csv file in the `/plate reader data/processed` folder